

limit_req_zone $binary_remote_addr zone=rails_limit:10m rate=5r/s;


upstream rails_app {
    server app:3000;
}

server {
    listen 80;
    server_name app.localhost;

    location / {
        
        limit_req zone=rails_limit burst=10 nodelay;

        proxy_pass http://rails_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}