upstream rails_app {
    server app:3000;
}

server {
    listen 80;
    location / {
        proxy_pass http://rails_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

